int lancer_des();
void afficher_des(int des[]);
void tri_tableau(int des[]);
int brelant(int des[]);
int carre(int des[]);
int full(int des[]);
int yams(int des[]);
void checkMilieuPartie(int* scoreA, int* scoreB);
int check_doublons(int des[]);
int chance(int des[]);
int lancer_joueur();
int petite_suite(int des[]);
int grande_suite(int des[]);
int tour();
void save(char* nom, int scorePartie);